name: e-commerce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      # 🔥 Buat file ZIP (hindari node_modules dll)
      - name: 📦 Create ZIP
        run: |
          zip -r project.zip . \
          -x "node_modules/*" ".git/*" ".github/*" ".env"

      # 🚀 Upload ZIP ke server (lebih stabil)
      - name: 🚀 Upload ZIP via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.jerryyss.my.id
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21
          security: loose

          local-dir: ./
          server-dir: /domains/sias.jerryyss.my.id/public_html/

          include: |
            project.zip

          log-level: verbose
          timeout: 600000
          dangerous-clean-slate: false
          log-level: verbose
          timeout: 600000

          # 🔥 penting biar stabil
          dangerous-clean-slate: false
